### ISSUE TITLE
Higher resolution logo in footer

### ISSUE THREAD

**Issue by abandea** [theirc/mahali-lab#7]
@tbeck - please let me know what the specs are for the logo? I can provide a higher res image. 

Thanks!

**Comment by tbeck** [comment]
Thanks @abandea 
It would be ideal if we could get each logo in a vector format (SVG, EPS). or... If logo files are only available in bitmap format it would be great to get them at a 500px width and we can optimize from there.

Thanks again!

**Comment by abandea** [comment]
Hi @tbeck! Certainly - you can find a folder of the vector files here: https://rescue.box.com/s/3qjjp5sg075ewkaifh3kmanbcs94zg7v 

For Start Network, they only gave us a PNG of the secondary logo (the one that is currently on the site), so feel free to use the primary one if it fits. I recommend the white since it will be against a dark background: https://rescue.box.com/s/0g0lo3b3nd19kbty4qztc9uajw0rmoqh

**Comment by tbeck** [comment]
Thanks @abandea!
We updated the logos to use svg for highest res. Can you review and let me know if this matches expectations?

https://mahali.rescue.org/

**Comment by abandea** [comment]
Thanks so much @tbeck - much better! Anyway we could reduce them to half or even a quarter of the current size? I don't think they need to be as prominent.

**Comment by tbeck** [comment]
Here is a screenshot with a more reasonable size for the logos. I also separated them on the white background to help differentiate. 
[![Screenshot from Gyazo](https://gyazo.com/e6e236e28485bf2bbb9dde5a09a240fd/raw)](https://gyazo.com/e6e236e28485bf2bbb9dde5a09a240fd)

Should these logos link to anything?

Thanks!

**Comment by abandea** [comment]
Looks good! No need to link them, thanks!
